version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: leyu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leyu
      MYSQL_USER: leyu
      MYSQL_PASSWORD: leyu123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  app:
    image: leyu-api
    container_name: leyu-api
    depends_on:
      - mysql
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: test
volumes:
  mysql_data: